name: JS Actions

on:
  workflow_dispatch:
  issues:
    types: [labeled]

jobs:
  action:
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: joke-action
        uses: ./.github/actions/joke-action
